spring:
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: postgres
    hikari:
      schema: contacts_schema